# Generated by Django 4.0.4 on 2022-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMonthTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('targetdistance', models.IntegerField(blank=True, null=True)),
                ('targetdate', models.DateField()),
            ],
        ),
    ]
