# Generated by Django 4.0.4 on 2022-05-24 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_recordmonthtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercisetype', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recordmonthtarget',
            name='targetdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
