# Generated by Django 4.0.4 on 2022-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_exercisetype_alter_recordmonthtarget_targetdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordactivity',
            name='exercisetype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
