# Generated by Django 4.0.4 on 2022-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_recordactivity_exercisetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordactivity',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
