# Generated by Django 4.0.4 on 2022-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_location_customuser_targetmiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='targetmiles',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
